
const ApiStrings = {
  // Authentication
    LOGIN: "/auth/login",
    REGISTER: "/auth/register",
    ME: "/auth/me",
    LOGOUT: "/auth/logout",
    UPLOAD_RESUME: "/auth/upload-resume",
    REFRESH_TOKEN: "/auth/refresh",
    CHANGE_PASSWORD: "/auth/change-password",
    SET_PASSWORD: "/auth/set-password",
    FORGOT_PASSWORD: "/auth/forgot-password",
    RESET_PASSWORD: "/auth/reset-password",
    COMPANY_PROFILE: "/auth/company-profile",
    // Jobs
    GET_JOBS: "/job/jobs",
    GET_APPLICATIONS: "/job/get-apply-jobs",
    RECENT_APPLIED: "/job/recent-applied",
    RECOMANDED_JOBS: "/job/recommended",
    STATS: "/job/stats",
    SAVED_JOBS: "/job/saved-jobs",
    COVER_LETTER: "/job/generate-cover-letter",
    POST_JOB: "/job/post",
    EMPLOYER_STATS: "/job/employer/stats",
    EMPLOYER_APPLICATION: "/job/employer/recent-applicants",
    ACTIVE_JOBS: "/job/employer/active-jobs",
    GET_COMPANIES: "/job/companies",
    MY_JOB: "/job/my-jobs",
    CANDIDATES: "/job/candidates",
    GET_JOB_APPLICATIONS: (id:string) => `/job/get-applications/${id}`,
    APPLICATIONS_EXPORT: "/job/applications/export",
    JOBS_EXPORT: "/job/my-jobs/export",
    SINGLE_JOB: (id:string) => `/job/${id}/detail`,
    APPLY_JOB: (id:string) => `/job/apply/${id}`,
    REVIEW: (id:string) => `/job/review/${id}`,
    DELETE: (id:string) => `/job/delete/${id}`,
    BOOKMARK: (id:string) => `/job/save/${id}`,
    GET_JOB_APPLICATION: (id:string) => `/job/job-apps/${id}`,
    UPDATE_APPLICATION_STATUS: (id:string) => `/job/status/${id}`,
    // Payment
    CREATE_PAYMENT_URL: '/pay/subcribe',
    BILLING_PORTAL: '/pay/billing-portal',
    PAYMENT_DETAILS: '/pay/details',
    // Notification
    UPDATE_NOTIFICATION: '/notification/update',
    // Employer
    SENT_INVITE: '/employer/invite',
    GET_INVITES: '/employer/invites',
    SET_PASSWORD_EMPLOYER: '/employer/set-password',
    DELETE_INVITE: (id:string) => `/employer/invite/${id}`,
    INTERVIEW_INVITE: (id:string) => `/employer/interview-invite/${id}`,
    SEND_MESSAGE: (id:string) => `/employer/message/${id}`,
  };
  
  export default ApiStrings;