const SocketsEventsConstant = {
    NEW_APPLICATION: "NEW_APPLICATION",
    JOB_VIEW_UPDATE: "JOB_VIEW_UPDATE",
    PROFILE_VIEW: "PROFILE_VIEW",
    APPLICATION_STATUS: "APPLICATION_STATUS",
    NOTIFICATION: "NOTIFICATION",
}

export default SocketsEventsConstant